### ISSUE TITLE
Porting 1000+ R datasets to observations

### ISSUE THREAD

**Issue by Arvinds-ds** [edwardlib/observations#19]
Hi Dustin,
I have written a python script to generate `observations` ready python files for over 1100 datasets available in R and related packages. The project page is https://github.com/Arvinds-ds/datasets_r2py. Could you kindly verify/comment on  the following

1. Whether the generated python source files conform to` edward/observationsrequirements`, the files are automatically generated in 'observations/rdata/', you can look at these files. If you have changes, kindly let me know the modifications to the templated python files` init_template.py`, `template.py` or `test_template.py`
2. If we were to use the files, how will it be structured in edward.I currently generated files in `observations/rdata` folder with tests in `observations/rdata/tests`
Let me know.

**Comment by dustinvtran** [comment]
That's amazing work! This is sure to be a tremendous help to the module, and obviously useful for anyone using R data sets in Python.

The overall design makes sense. I agree that the generated files should exist in a subdirectory of `observations/`. As Observations gets very large, I can imagine users still loading any data via `from observations import x`. But internally, the functions will be organized in subdirectories, and the API will list all functions according to this organization rather than a enormous laundry list.

On 1, there are a few necessary formatting changes listed from easiest to hardest to implement. We can leave the hardest todos as future work and merge the rest now.

+ `import pandas as pd` should go inside the function's body. pandas is not part of the python standard library or numpy.
+ There should be a blankline between the `Args:` subsection and the line `Returns:`.
+ `os.path.join(path,filename)` -> `os.path.join(path, filename)`
+ `filename = "{{filename}}"` -> `filename = '{{filename}}'`. Same goes for `url`.
+ Inserted things like `{{filename}}` and `{{url}}` will need a line break if the line exceeds 80 characters.
+ There may be difficulties with returning the NumPy array from the pandas data frame. For example, some features may be strings or factors while others are integers or real values; how does the returned NumPy array process these different types?
+ What does `sys.path.append('../../')` do?
+ Did the autogenerated `__init__.py` work? The one in `observations/__init__.py` hasn't changed.
+ Any references in the docstring such as `S. Abbey (1988) *Geostandards Newsletter* **12**, 241.` should have a bib entry in `bib.bib` and referenced using the citekey `@abbey1988robust`.
+ Any data set descriptions of each feature should be formatted as a Markdown table (see, e.g., http://edwardlib.org/api/observations/boston_housing).

On 2, I'm open to suggestions. One thought is to include a directory in this repo, called `doc/` or `src/`. It will contain the template python files and the generation scripts. None of the actual data (csvs) will exist in the directory. 

As we attempt to merge this work, we can include a `tests/` directory and place the autogenerated tests there. There's an open question of how Travis should run these tests; maybe each build will only run a random subset of the tests?

**Comment by Arvinds-ds** [comment]
@dustinvtran. Thanks for detailed comments . I have reworked the generation code. Pls see the generated code in repo
1. Fixed
2. Fixed
3. Fixed
4.  Can be done. Fixed
5. Fixed
6. This is for testing. Removed
7. The generated __init__.py is a placeholder to generated imports and modules depending on how you want to structure it eventually for the final merge
8. I have no idea on how to do this. When I parse rst, I generate the source field but I don't know how to make it bib8 complaint. Some of datasets do not have a source entry
9. That should not be an issue (unless you are inflexible on the format). You can see the rendered RST as html in docs folder (These are R help files).

2. I am perfectly ok with the structure you want. The generation is easy. My only concern is whether we host the csv's to the author's github url or host it in Edward's github. The tests shouldn't be data hungry as the combined footprint of the 1100 datasets in just 130 MB.

**Comment by dustinvtran** [comment]
> I have no idea on how to do this. When I parse rst, I generate the source field but I don't know how to make it bib8 complaint. Some of datasets do not have a source entry

That step seems not possible to automate. Let's leave it as future work.

> That should not be an issue (unless you are inflexible on the format). You can see the rendered RST as html in docs folder (These are R help files).

Cool! As long as they render as tables in the docs using Edward's compile script (https://github.com/blei-lab/edward/tree/master/docs). Whether that involves hacking the generated docstrings or extracting pieces from the rst/html is up to you.

> I am perfectly ok with the structure you want. The generation is easy. My only concern is whether we host the csv's to the author's github url or host it in Edward's github. The tests shouldn't be data hungry as the combined footprint of the 1100 datasets in just 130 MB.

Oh, great. Happy to review a PR with Travis testing the full directory then.

**Comment by dustinvtran** [comment]
Forgot to answer this:

> My only concern is whether we host the csv's to the author's github url or host it in Edward's github.

Let's host it at the author's github url. Hosting data in our repo doesn't scale well. We can host all our data sets in the future, but if so, we should do it on an external server like AWS.

**Comment by Arvinds-ds** [comment]
Great. Can you specify the folder structure then. Are the following names ok?
observations/rdata - source files
observations/rdata/tests - test file
observations/rdata/src - template files/csv master file
observations/rdata/docs - rst files to generate doc strings

Regarding data hosting. My only concern is if the author suspends his github repo.

**Comment by dustinvtran** [comment]
> Great. Can you specify the folder structure then. Are the following names ok?

How about
+ `observations/rdata/` (or `observations/r`): source files
+ `tests/`: Test files.
+ `src/`: templates and generation scripts

Right now, it seems like the rst/html are intermediate files to build the pages hosted on Edward's `gh-pages` branch. They'll be re-built and destroyed every time we compile the docs; so we don't have to git commit them.

> Regarding data hosting. My only concern is if the author suspends his github repo.

It's definitely a concern and is a failure mode for all our data sets. At some point we can look into storing them on an external server.

**Comment by Arvinds-ds** [comment]
`src` - needs to have rst files as the script generates python doc strings from R package rst files.  Either we check in rst files along with the package structure or leave the template and generation scripts in my repo and commit only the `observations/r` and `observation/tests` files in this repo

**Comment by Arvinds-ds** [comment]
Also pls look at the generated `test_*.py`  files  in my repo and see if you have a specific test file format/doc strings for test files. Currently it is just a vailla python file suitable for pytest.

**Comment by dustinvtran** [comment]
> src - needs to have rst files as the script generates python doc strings from R package rst files. Either we check in rst files along with the package structure or leave the template and generation scripts in my repo and commit only the observations/r and observation/tests files in this repo

Oh I see. Sounds like they belong in the same decision as where to store the data. How large is the collection of rst files? And is it possible to get them from some location instead of directly storing them? One thing we can do temporarily is store them now in `src/`, and later think about how we might store and load them in from another location.

> Also pls look at the generated test_*.py files in my repo and see if you have a specific test file format/doc strings for test files. Currently it is just a vailla python file suitable for pytest.

Yep, it works. I like pytest too. I suggest removing the sys path append and directly importing the function via `from observations import x`.
