### ISSUE TITLE
Include autogeneration scripts of R data sets in repo

### ISSUE THREAD

**Issue by dustinvtran** [edwardlib/observations#21]
Following discussion in #19.

**Comment by Arvinds-ds** [comment]
I will work on cleaning up the code and making it Python 2 compatible but haven't found the time. Also, the build is failing for observations master repo due to random Connection errors (probably due to the volume of data hitting the user's github repo during travis testing). Is there a way to host these reliably. I can change the URLs in the master file and regenerate the files

**Comment by dustinvtran** [comment]
Got it. Do keep me posted. I might be able to find time to help.

**Comment by Arvinds-ds** [comment]
See PR #24

**Comment by dustinvtran** [comment]
Fixed in #25.
